package com.riichimahjong.registry;

import com.riichimahjong.RiichiMahjong;
import dev.architectury.core.fluid.ArchitecturyFlowingFluid;
import dev.architectury.core.fluid.SimpleArchitecturyFluidAttributes;
import dev.architectury.registry.registries.DeferredRegister;
import dev.architectury.registry.registries.RegistrySupplier;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.material.Fluid;

/**
 * Liquid Experience — a marker fluid that XP-aware mods (via {@code c:experience} tag)
 * recognize as moveable XP. Generated by the solitaire / yaku-gen automation surfaces
 * (re-added in this phase) and consumed by fluid pipes / tanks.
 *
 * <p>1.21 cross-loader fluids: Architectury provides {@link ArchitecturyFlowingFluid}
 * and {@link SimpleArchitecturyFluidAttributes}, which wrap the per-loader fluid type
 * registration (NeoForge {@code FluidType}, Fabric {@code FluidVariant} attributes).
 * One config in common; both loaders see the same fluid id and behaviour.
 */
public final class ModFluids {
    public static final DeferredRegister<Fluid> FLUIDS =
            DeferredRegister.create(RiichiMahjong.MOD_ID, Registries.FLUID);

    private static final ResourceLocation STILL_TEX =
            ResourceLocation.fromNamespaceAndPath(RiichiMahjong.MOD_ID, "block/liquid_experience_still");
    private static final ResourceLocation FLOW_TEX =
            ResourceLocation.fromNamespaceAndPath(RiichiMahjong.MOD_ID, "block/liquid_experience_flow");

    public static final RegistrySupplier<Fluid> LIQUID_EXPERIENCE = FLUIDS.register(
            "liquid_experience",
            () -> new ArchitecturyFlowingFluid.Source(attributes()));

    public static final RegistrySupplier<Fluid> LIQUID_EXPERIENCE_FLOWING = FLUIDS.register(
            "liquid_experience_flowing",
            () -> new ArchitecturyFlowingFluid.Flowing(attributes()));

    private static SimpleArchitecturyFluidAttributes attributesCache;

    /**
     * Built lazily so source/flowing both reference the same instance without circular
     * static-init issues.
     */
    private static SimpleArchitecturyFluidAttributes attributes() {
        if (attributesCache == null) {
            attributesCache = SimpleArchitecturyFluidAttributes.of(
                            () -> LIQUID_EXPERIENCE_FLOWING.get(),
                            () -> LIQUID_EXPERIENCE.get())
                    .sourceTexture(STILL_TEX)
                    .flowingTexture(FLOW_TEX)
                    .color(0xFFC8FF40)
                    .density(800)
                    .viscosity(1500)
                    .luminosity(7)
                    .bucketItem(ModItems.LIQUID_EXPERIENCE_BUCKET)
                    .block(ModBlocks.LIQUID_EXPERIENCE_BLOCK);
        }
        return attributesCache;
    }

    private ModFluids() {}
}
